version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: client-service-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minifood_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - minifood_net

volumes:
  mysql_data:

networks:
  minifood_net:
    driver: bridge
